### PR TITLE
snapcraft.yaml: add indicator-qt5 remote part

### PR DESCRIPTION
**Pull request by 3v1n0**
It allows to show the proper indicator icon in unity.

Also fix compilation due the 3rdparty libraries being excluded.
This to work however needs this fix to snapcraft to be applied: https://github.com/snapcore/snapcraft/pull/926

### CODE REVIEW

**Comment by theshadowx** [comment]
Great, so it fixes the issue #78 ?

**Comment by nuttyartist** [comment]
Yeah, @3v1n0 can you reassure it fixes #78?

**Comment by 3v1n0** [comment]
@nuttyartist, @theshadowx. Yes, it fixes that.

**Comment by nuttyartist** [comment]
Cool, merging...

**Pull request merged**
