### PR TITLE
Fix bug 163 - Automatic startup on Windows and Linux

### PR DESCRIPTION
**Pull request by b00f**
Changes:
fix bug #163 (automatic startup)
fix misplacing traffic lights in Windows
 

- [x] Works on Windows.
- [x] Works on Linux.

### CODE REVIEW

**Comment by theshadowx** [comment]
Could you add in appveyor.yaml  in install section (just after the line 48): 
```
- git submodule update --init --recursive
```
And also in README, could you replace the line 20 by:
```
$> git clone --recursive  https://github.com/nuttyartist/notes.git
```

Thanks

PS: i haven't yet tested this feature, but just to have the continuous integration work with your modifications.

**Comment by nuttyartist** [comment]
I currently tested only on Mac and Windows. It worked well on Windows. 
Are you sure it's working on Linux or shall I test it also? 

On my Mac, it didn't work, and there were also some minor problems regarding code compilation:
1. Need to add `#include <QProcess>`.
2. Inside the function on [line 94](https://github.com/b00f/qautostart/blob/0efcfbdf93b611ca7564402c6b4ab4e5e7f7074c/src/qautostart.cpp#L94) you should change `dir ` to `appDir `, I think.

Do you have an idea on what needs to be fixed in order for it to work on Mac?
Also, seems like the ✓ sign on the menu is always toggled on the Mac so it's not clear what's the current state of the menu action (is it on or off). It doesn't happen with the view->Always stay on top menu bar.

**Comment by nuttyartist** [comment]
So it's working on Windows and Linux.

I'll merge this and create a new issue for automatic startup specifically for Mac.
This is awesome, thanks, Mostafa.

I plan to work a new minor release with all the different **bug-fixes/enhancements/new-features** from our "In-Between Releases" project then we'll push a release people would be able to get using our automatic updates system.

Oh but before I merge this, @b00f can you do the code changes I mentioned in the comment above for numbers 1 and 2? Then I'll merge.

**Comment by b00f** [comment]
Sure. I will update it.
Since I don't have mac I can't verify them. Can you get project and update it for mac later?

**Comment by nuttyartist** [comment]
Do you mean to ask if I can implement your project and test it on Mac? I can surely test it. Probably not so much implement it. But I'll try to tweak some things here and there to see if I can make it work.

**Comment by nuttyartist** [comment]
Oh, and make sure to include this feature only for Windows and Linux for now.

**Comment by theshadowx** [comment]
It's better to create another PR.

**Comment by b00f** [comment]
Is it possible to create new PR from my forked branch (dev)?

**Comment by theshadowx** [comment]
@b00f you can create a branch then do your modifications and then submit PR

**Comment by b00f** [comment]
How about this commit I have submitted?  =
`highlight search`

**Comment by theshadowx** [comment]
It was a feature request #81 , I haven't tested yet. sure it would be most welcome if it works as described.

**Comment by b00f** [comment]
Please close this pull request. I will create new branch for pinned messages and markdown features.

**Comment by nuttyartist** [comment]
What about the "Automatic startup on Windows and Linux"? We need to merge that first.
Have you applied these changes to the code?:
1. Need to add #include <QProcess>.
2. Inside the function on line 94 you should change dir to appDir, I think.

If so, I'll merge this PR. For any additional feature it is best to create a new, different PR, so we'll have a good view of each feature/change with the related code. So you should create a new PR for highlighting text when searching for a note (I will be happy to test that) and for other features you're planning to implement.

**Comment by b00f** [comment]
I have updated the above changes. You can check it by syncing the submodules. 
I am sorry, this PR get a little bit messy.  I will create new branches for my changes.

**Comment by nuttyartist** [comment]
I have checked the changes but it seems like the **search with highlighted text is there** _where it should be on a different PR_ and the **changes in the comment [above](https://github.com/nuttyartist/notes/pull/192#issuecomment-361002096) are not implemented** (it's just a little thing).

So just keep only the things related for automatic startup on Windows and Linux and do the little changes in the comment I mentioned and I'll merge. For the other features, it'll be a good approach to create a new PR for each one.

**Comment by b00f** [comment]
I removed highlight method from this PR. Please merge it with --no-ff method to ignore unrelated changes. Thanks

**Comment by nuttyartist** [comment]
You still didn't do the changes required in qautostart.cpp:

1. Need to add #include .
2. Inside the function on line 94 you should change the variable `dir` to `appDir`, I think.

**Comment by b00f** [comment]
I think you need to update submodue:
`git submodule update --recursive`

**Pull request merged**
