### PR TITLE
Fixing database

### PR DESCRIPTION
**Pull request by theshadowx**
This is fixing the database according to the latest updates on Qt on sql.
The database manager is now working in its own thread dependent from the main one.
The communication between main thread and the one related to DBManager is done through signals and slots.

### CODE REVIEW

**Comment by nuttyartist** [comment]
Hey!

I'm having problems cloning your repo. I'm using this command:

`git clone --single-branch --branch fixing_database https://github.com/theshadowx/notes.git`

But when I try to compile using Qt I get:

```
/Users/ruby/Downloads/notes/src/mainwindow.h:26: error: 'QAutostart' file not found
#include <QAutostart>
         ^~~~~~~~~~~~
```

**Comment by theshadowx** [comment]
you should add --recursive 

Btw I can't access to Slack my account to note group was desactivated

**Comment by nuttyartist** [comment]
Sorry, for that! Slack should work now.

Everything seems to work well.

2 notes:
1. At first, I got compiling errors because of `qautostart.cpp`. It's needed to add `#include <QProcess>` and replace variable name from`dir` to `appDir`.
2. Just tiny thing I found is when I click the 3 dots button I get in the debug this message: `syntax error: Expected end of line but found class name. (-2741)`. Didn't see any difference visually tho.

Should you let me know what we gonna do about (1) update it upstream or in our repo? And I'll merge this.

**Comment by theshadowx** [comment]
weird that you get this issues, I didn't have them.
Which Qt have you used and what OS ?

**Comment by nuttyartist** [comment]
Just updated to the latest Qt version 5.13.1. Using Mac OS Mojave. The second problem is minor/not important. But the first one causes the program not to compile (on my machine at least). Which makes sense cause code I mentioned from qautostart is wrong.

**Comment by theshadowx** [comment]
which .pro file did you load ?

**Comment by nuttyartist** [comment]
Both in root and src.

**Comment by theshadowx** [comment]
The errors you mentioned are not related to the pull request.

autostart is not supported in MacOS, I will fix that issue after this is been accepted.
Also as we imported that repo we can't modify it.

the second issue is related to osascript.

I'll disable autostart for mac.

**Comment by nuttyartist** [comment]
Maybe we can import it into our repo and then change it?

**Comment by theshadowx** [comment]
I will take a look at that later

**Comment by nuttyartist** [comment]
Ok. 

Good work (; Merging...

**Pull request merged**
