### PR TITLE
Update QMarkdownTextedit library

### PR DESCRIPTION
**Pull request by Waqar144**
Update QMarkdownTextedit library to latest release. Lot of things have changed, some are:
- Partial rewrite of markdown parser to be more Commonmark compliant
- Major performance improvements(100% faster)
- Support for tilde style code fences
- Support for nested code blocks
- Support for Ordered lists
- Support for underlines
- Support for strikethrough
- Syntax highlighting support for CMake and Make

### CODE REVIEW

**Comment by nuttyartist** [comment]
Awesome. Why do we get here errors from AppVeyor wherein the dev branch there are no errors?

**Comment by Waqar144** [comment]
> Awesome. Why do we get here errors from AppVeyor wherein the dev branch there are no errors?

I really have no idea. The code is correct I am pretty sure of that, and even the Qt version is low enough that it should compile....

**Comment by pbek** [comment]
nice, @Waqar144 is working on all fronts :grin:

**Comment by nuttyartist** [comment]
Merging, thanks!

**Pull request merged**
