### PR TITLE
Added deployment to GitHub on tags

### PR DESCRIPTION
**Pull request by bjorn**
See issue #248.

### CODE REVIEW

**Comment by bjorn** [comment]
So, after merging this, the builds done on Travis CI based on the `v1.5.0` tag _should_ be directly uploaded to GitHub. I've set `draft: true` so that the release will not be immediately published, so that we can also test this somewhat silently.

Let me know when you want me to push this and a tag to test the process. We can just delete the tag again when something goes wrong.

**Comment by nuttyartist** [comment]
Let's do it!

**Comment by bjorn** [comment]
Ok, I merged, tagged `v1.5.0`, had to [fix a typo](f1bc03fcb161fb1d39e4dfa549a87e64754e934c), and retagged. Let's see what happens now...

**Comment by bjorn** [comment]
Alright, next problem is that the `.deb` is still always called `notes_1.0.0_amd64.deb` regardless of the target version of Ubuntu, whoops.

**Comment by bjorn** [comment]
Now packages should be getting renamed (346841dd99a5fdf955d89c8714b04d08730de5a7).

**Comment by nuttyartist** [comment]
So it didn't work and you removed the tag? I just saw your new PR, gonna respond there.

**Pull request merged**
