### PR TITLE
fix: specify the easing curve correctly

### PR DESCRIPTION
**Pull request by guihkx**
This fixes a derp I introduced with #340.

Thanks @bjorn for spotting this!

### CODE REVIEW

**Review by bjorn — APPROVED** [review]
That looks better. :)

**Comment by bjorn** [comment]
Hmm, not sure why GitHub added `Co-authored-by: guihkx <guihkx@users.noreply.github.com>`...

**Comment by guihkx** [comment]
IIRC, that line is added automatically when you squash a PR using Github.

**Comment by bjorn** [comment]
> IIRC, that line is added automatically when you squash a PR using Github.

Yeah, but usually only when there is a mismatch between the email used on the commit and the email set on the GitHub account. Actually you seem to be `guih.rox@gmail.com` to GitHub, but you seem to be committing with `guihkx@users.noreply.github.com`, so that's probably it.

**Comment by nuttyartist** [comment]
> This fixes a derp I introduced with #340.
> 
> Thanks @bjorn for spotting this!

@bjorn Good catch. Thank you both!

**Pull request merged**
