### PR TITLE
Implementing SQLite Database #73

### PR DESCRIPTION
**Pull request by theshadowx**

### CODE REVIEW

**Comment by nuttyartist** [comment]
Awesome, it works as it should now.
Before merging, why does Travis build wasn't succesful?
@theshadowx

**Comment by theshadowx** [comment]
it's because of the repository, I'm checking it now. If you click on details you'll see the error points to the qt5 repository

**Comment by nuttyartist** [comment]
Oh alright then. Merging... :)

**Comment by nuttyartist** [comment]
Thanks for the great work!

**Pull request merged**
