### PR TITLE
Update UPDATES file for 2.1.0 release

### PR DESCRIPTION
**Pull request by nuttyartist**
There is one problem with the text. The line spacing doesn't allow the points to be close together for some reason.

Here's how it looks on my computer:

Screen Shot 2023-03-04 at 6 49 06 PM

Dows someone knows the correct HTML to fix this? If we can't, I'll revert to plain text, but I thought it would be nice to have links to our Discord and bold formatting using HTML.

### CODE REVIEW

**Comment by zjeffer** [comment]
Is there a way to test changes to the UPDATES.json file without pushing? I think you could maybe fix it by not using <p></p> tags for every line (instead use <ul> or <br>'s or something), but I don't know how to test that.

**Comment by guihkx** [comment]
>Is there a way to test changes to the UPDATES.json file without pushing?

You could start a local server to serve a custom `UPDATES.json`, e.g.:

```
# run this in the same directory where UPDATES.json is
python3 -m http.server 8000
```

And then you'd have to also edit `updaterwindow.cpp` and point the URL in `UPDATES_URL` to `http://localhost:8000/UPDATES.json`.

**Comment by zjeffer** [comment]
I improved it a bit, but now I feel the bullet points are indented too much. I can't seem to change the styling of the <li> tags in C++ for some reason. I tried it with this in the updaterwindow constructor:

```cpp
m_ui->changelog->setStyleSheet(QStringLiteral("QTextBrowser li { margin-left: 0; padding-left: 0; }"));
```


But that doesn't seem to do anything. It currently looks like this:

image

**Comment by guihkx** [comment]
Yeah, I also tried to remove that padding but I couldn't either...

And I believe we can style elements directly in `<style>`, so using `setStyleSheet()` doesn't seem necessary there.

Here's what I got so far (indented for legibility):

```html
<style>
div {
  color: #000;
}
kbd {
  color: #24292f;
  background-color: #f6f8fa;
}
</style>
<div>
  <p>A new release is here with some new features and many bug fixes and improvements.</p>
  <p>New features:</p>
  <ul>
    <li>You can now open external links by holding <kbd>Ctrl</kbd> while clicking them.</li>
    <li>
      <span>You can now format text using keyboard shortcuts:</span>
      <ul>
        <li>Bold: <kbd>Ctrl</kbd> + <kbd>B</kbd>.</li>
        <li>Italic: <kbd>Ctrl</kbd> + <kbd>I</kbd>.</li>
        <li>Strikethrough: <kbd>Ctrl</kbd> + <kbd>S</kbd>.</li>
      </ul>
    </li>
    <li>You can create different heading levels with <kbd>Ctrl</kbd> + <kbd>1</kbd>...<kbd>6</kbd>.</li>
    <li>You can increase or decrease levels by using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + (<kbd>+</kbd> or <kbd>-</kbd>).</li>
    <li>You can now access the app menu by pressing <kbd>F10</kbd> (<kbd>Fn</kbd> + <kbd>F10</kbd> on macOS).</li>
  </ul>
  <p>Improvements and bug fixes:</p>
  <ul>
    <li>Automatic updates now work on Windows.</li>
    <li>Fixed bugs with native window decoration.</li>
    <li>We improved the style of selecting multiple notes.</li>
    <li>Fixed a bug on Windows causing extreme input delay when editing text.</li>
    <li>Streamlined the look and feel of some windows to match the OS better.</li>
    <li>Fixed issues when resizing the window's splitters and resizing the window itself.</li>
    <li>Fixed some bugs causing crashes.</li>
    <li>Many more fixes and improvements under the hood.</li>
  </ul>
  <p>Big thanks to the people who contributed to this release! We have big plans for the future of Notes. We aim to make Notes, not just the best open-source note-taking app but the best note-taking app, period.</p>
  <p>Join our <span><a href='https://discord.gg/RP6ReXRn5j'>Discord</a></span> for discussions, and feel free to email us. We love to hear from our users.</p>
</div>
<br>
```

Or, this one-liner to put in `UPDATES.json`: 

```html
<style>div{color: #000;}kbd{color: #24292f; background-color: #f6f8fa;}</style><div> <p>A new release is here with some new features and many bug fixes and improvements.</p><p>New features:</p><ul> <li>You can now open external links by holding <kbd>Ctrl</kbd> while clicking them.</li><li> <span>You can now format text using keyboard shortcuts:</span> <ul> <li>Bold: <kbd>Ctrl</kbd> + <kbd>B</kbd>.</li><li>Italic: <kbd>Ctrl</kbd> + <kbd>I</kbd>.</li><li>Strikethrough: <kbd>Ctrl</kbd> + <kbd>S</kbd>.</li></ul> </li><li>You can create different heading levels with <kbd>Ctrl</kbd> + <kbd>1</kbd>...<kbd>6</kbd>.</li><li>You can increase or decrease levels by using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + (<kbd>+</kbd> or <kbd>-</kbd>).</li><li>You can now access the app menu by pressing <kbd>F10</kbd> (<kbd>Fn</kbd> + <kbd>F10</kbd> on macOS).</li></ul> <p>Improvements and bug fixes:</p><ul> <li>Automatic updates now work on Windows.</li><li>Fixed bugs with native window decoration.</li><li>We improved the style of selecting multiple notes.</li><li>Fixed a bug on Windows causing extreme input delay when editing text.</li><li>Streamlined the look and feel of some windows to match the OS better.</li><li>Fixed issues when resizing the window's splitters and resizing the window itself.</li><li>Fixed some bugs causing crashes.</li><li>Many more fixes and improvements under the hood.</li></ul> <p>Big thanks to the people who contributed to this release! We have big plans for the future of Notes. We aim to make Notes, not just the best open-source note-taking app but the best note-taking app, period.</p><p>Join our <span><a href='https://discord.gg/RP6ReXRn5j'>Discord</a></span> for discussions, and feel free to email us. We love to hear from our users.</p></div><br>
```

I basically just fixed a typo (`decereas` -> `decrease`), and I tried to make the style of keyboard shortcuts look *a bit* better:

https://user-images.githubusercontent.com/626206/222934617-25bf075c-a18d-468b-8c07-94b48e956cf9.mp4

<br>

But yeah, the huge left padding makes it look hideous, so we probably have to improve upon the approach @nuttyartist first went with.

Curiously, I was able to remove the list bullet points with `ul { list-style: none; }`, but still no success in removing the padding. 🤷

**Comment by zjeffer** [comment]
Seems like setting `-qt-list-indent: 0;` in `ul` removes the indentation, but removes the bullet point if the value is 0.

**Comment by nuttyartist** [comment]
> Yeah, I also tried to remove that padding but I couldn't either...
> 
> And I believe we can style elements directly in `<style>`, so using `setStyleSheet()` doesn't seem necessary there.
> 
> Here's what I got so far (indented for legibility):
> 
> ```
> <style>
> div {
>   color: #000;
> }
> kbd {
>   color: #24292f;
>   background-color: #f6f8fa;
> }
> </style>
> <div>
>   <p>A new release is here with some new features and many bug fixes and improvements.</p>
>   <p>New features:</p>
>   <ul>
>     <li>You can now open external links by holding <kbd>Ctrl</kbd> while clicking them.</li>
>     <li>
>       <span>You can now format text using keyboard shortcuts:</span>
>       <ul>
>         <li>Bold: <kbd>Ctrl</kbd> + <kbd>B</kbd>.</li>
>         <li>Italic: <kbd>Ctrl</kbd> + <kbd>I</kbd>.</li>
>         <li>Strikethrough: <kbd>Ctrl</kbd> + <kbd>S</kbd>.</li>
>       </ul>
>     </li>
>     <li>You can create different heading levels with <kbd>Ctrl</kbd> + <kbd>1</kbd>...<kbd>6</kbd>.</li>
>     <li>You can increase or decrease levels by using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + (<kbd>+</kbd> or <kbd>-</kbd>).</li>
>     <li>You can now access the app menu by pressing <kbd>F10</kbd> (<kbd>Fn</kbd> + <kbd>F10</kbd> on macOS).</li>
>   </ul>
>   <p>Improvements and bug fixes:</p>
>   <ul>
>     <li>Automatic updates now work on Windows.</li>
>     <li>Fixed bugs with native window decoration.</li>
>     <li>We improved the style of selecting multiple notes.</li>
>     <li>Fixed a bug on Windows causing extreme input delay when editing text.</li>
>     <li>Streamlined the look and feel of some windows to match the OS better.</li>
>     <li>Fixed issues when resizing the window's splitters and resizing the window itself.</li>
>     <li>Fixed some bugs causing crashes.</li>
>     <li>Many more fixes and improvements under the hood.</li>
>   </ul>
>   <p>Big thanks to the people who contributed to this release! We have big plans for the future of Notes. We aim to make Notes, not just the best open-source note-taking app but the best note-taking app, period.</p>
>   <p>Join our <span><a href='https://discord.gg/RP6ReXRn5j'>Discord</a></span> for discussions, and feel free to email us. We love to hear from our users.</p>
> </div>
> <br>
> ```
> 
> Or, this one-liner to put in `UPDATES.json`:
> 
> ```
> <style>div{color: #000;}kbd{color: #24292f; background-color: #f6f8fa;}</style><div> <p>A new release is here with some new features and many bug fixes and improvements.</p><p>New features:</p><ul> <li>You can now open external links by holding <kbd>Ctrl</kbd> while clicking them.</li><li> <span>You can now format text using keyboard shortcuts:</span> <ul> <li>Bold: <kbd>Ctrl</kbd> + <kbd>B</kbd>.</li><li>Italic: <kbd>Ctrl</kbd> + <kbd>I</kbd>.</li><li>Strikethrough: <kbd>Ctrl</kbd> + <kbd>S</kbd>.</li></ul> </li><li>You can create different heading levels with <kbd>Ctrl</kbd> + <kbd>1</kbd>...<kbd>6</kbd>.</li><li>You can increase or decrease levels by using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + (<kbd>+</kbd> or <kbd>-</kbd>).</li><li>You can now access the app menu by pressing <kbd>F10</kbd> (<kbd>Fn</kbd> + <kbd>F10</kbd> on macOS).</li></ul> <p>Improvements and bug fixes:</p><ul> <li>Automatic updates now work on Windows.</li><li>Fixed bugs with native window decoration.</li><li>We improved the style of selecting multiple notes.</li><li>Fixed a bug on Windows causing extreme input delay when editing text.</li><li>Streamlined the look and feel of some windows to match the OS better.</li><li>Fixed issues when resizing the window's splitters and resizing the window itself.</li><li>Fixed some bugs causing crashes.</li><li>Many more fixes and improvements under the hood.</li></ul> <p>Big thanks to the people who contributed to this release! We have big plans for the future of Notes. We aim to make Notes, not just the best open-source note-taking app but the best note-taking app, period.</p><p>Join our <span><a href='https://discord.gg/RP6ReXRn5j'>Discord</a></span> for discussions, and feel free to email us. We love to hear from our users.</p></div><br>
> ```
> 
> I basically just fixed a typo (`decereas` -> `decrease`), and I tried to make the style of keyboard shortcuts look _a bit_ better:
> 
> 
> But yeah, the huge left padding makes it look hideous, so we probably have to improve upon the approach @nuttyartist first went with.
> 
> Curiously, I was able to remove the list bullet points with `ul { list-style: none; }`, but still no success in removing the padding. 🤷

Looking good! The indentation is annoying. I'm trying to find a solution as well.

**Comment by nuttyartist** [comment]
Setting

```html
<ul style='margin-left:-2em'>
```

solves the issue on my machine. Can you guys test this?

Screen Shot 2023-03-05 at 5 36 53 PM

**Comment by guihkx** [comment]
Oh, very nice! And if we set that rule globally, i.e.:

```html
<style>
ul {
  margin-left: -2em;
}
</style>
```

In my opinion the indentation looks even nicer:

image

**Comment by nuttyartist** [comment]
> ```
> <ul style='margin-left:-2em'>
> ```

I think it's a bit too much. I think we can set it globally and add `<ul style='margin-left:-1em'>` for the formatting shortcuts `ui`.

**Comment by guihkx** [comment]
That looks good to me as well!

**Comment by guihkx** [comment]
I'd recommend using the Qt 6 AppImage, by the way.

It will require at least Ubuntu 20.04 LTS, though. Which is not unreasonable, since official support for the previous LTS release (18.04), will end in a month.

**Comment by nuttyartist** [comment]
> I'd recommend using the Qt 6 AppImage, by the way.

Alrighty.

I will still upload the Qt5 one to the Releases page.

> I'd also squash those 4 commits into a single one before merging.

👍 

Just wrote on the Discord the process before releasing

https://discord.com/channels/1032620427501129779/1032620428495163436

> So just want to see if my process is correct. 
> 
> 1. I will merge https://github.com/nuttyartist/notes/pull/510 into dev
> 2. I will merge dev into master
> 3. Create a new release and tag based on the master branch
> 4. Upload the binaries created by Github Actions (and re-create and sign the macOS one)
> 5. Create a PR for the dev branch with the new UPDATES.json file and the new binaries links.
> 6. Merge into master.
> 7. All our users getting an update (:
> 
> Is that the correct way to do it?

**Comment by guihkx** [comment]
>I will still upload the Qt5 one to the Releases page.

Perfect.

>Just wrote in Discord the process before releasing

Wait, if you merge this PR into `dev`, and then merge `dev` into `master` *before* releasing the 2.1.0 binaries, wouldn't it mess up the auto updater?

**Comment by nuttyartist** [comment]
> > I will still upload the Qt5 one to the Releases page.
> 
> Perfect.
> 
> > Just wrote in Discord the process before releasing
> 
> Wait, if you merge this PR into `dev`, and then merge `dev` into `master` _before_ releasing the 2.1.0 binaries, wouldn't it mess up the auto updater?

Oh, you're right. So should I create a new release based on the dev branch?

**Comment by guihkx** [comment]
Not necessarily. I'd do it like this:

1. You merge `dev` into `master` now.
2. You create the 2.1.0 tag.
3. Wait for the CI to generate the 2.1.0 binaries
4. You create the GitHub release for 2.1.0
5. You change this PR to update the download links
6. You merge this PR into `master`

**Comment by nuttyartist** [comment]
Sounds good!

**Pull request merged**
