### PR TITLE
Check the merge

### PR DESCRIPTION
**Pull request by theshadowx**
Creating this pull request to let you check if everything still working as wished specially for updater.

I receive the dialog telling me that an update is available but the update button is disabled. I guess it's because @alex-spataru dev  branch should be pushed to this one. let me know if that right so I'll push it before merging to @nuttyartist dev branch.

### CODE REVIEW

**Comment by nuttyartist** [comment]
There are some modifications needed to be done before merging to the dev branch.

@alex-spataru Can you update your branch with all the new commits and take care of these things that need to be done, and then send another PR?

Aesthetic wise:
- The pop-up flag should be frameless (like the main window)
- Background color should be rgb(247, 247, 247)
- All the fonts should be the already embedded Roboto font
- The "What's new:" box border should have the color rgb(205, 205, 205), it's background color should be rgb(251, 251, 251) and it's text color should be rgb(117, 117, 117)
- The progress should be more beautiful, look "whole" - like in the mockups below.
- The buttons should be only text-based, they should show the same colors as the other buttons on the main window: default color: rgb(68, 138, 201), hovered color: rgb(51, 110, 162), pressed color: rgb(39, 85, 125)
- The layout and space between all the elements should be the same as in these pictures:

screenshot-from-2016-08-17-16_20_24
screenshot-from-2016-08-17-16_22_01

Functionality wise:  
- I replaced 
`const QString UPDATES_URL = "https://raw.githubusercontent.com/nuttyartist/notes/dev/UPDATES.json";`
with
`const QString UPDATES_URL = "https://raw.githubusercontent.com/nuttyartist/notes/automatic-updates-windows/UPDATES.json";`
So now the "Update" button is working. I'm using Linux, and as I'm clicking "Update" it seems to download the package but it get stuck and doesn't run it. Here's a screenshot:
yo

Other:
- The "dotsButton" focusPolicy should be set to "NoFocus" in the QtCreator window form.
- We should add the "Check for updates" action to the dotsButton menu.
Just add this line to the "Create Menu" function:
viewMenu->addAction(m_checkForUpdatesAction);

That's it for now.

**Comment by alex-spataru** [comment]
@nuttyartist I will work on the style of the updater dialog and send another pull request. Thanks for the mockups!

**Comment by theshadowx** [comment]
@alex-spataru please pull @nuttyartist automatic branch before doing modification.

**Comment by alex-spataru** [comment]
@theshadowx Thanks for the info, I will do that before doing modifications.

**Comment by alex-spataru** [comment]
Hello,

I have done some progress on the UI, here is a screenshot of the updater window:

screenshot

The CSS/QSS stylesheet applied to the window is:

```
QWidget {
   font: 13pt "Roboto";
   background-color: rgb(247, 247, 247);
}

QTextBrowser {
   color: rgb(117, 117, 117);
   border-color: rgb(205, 205, 205);
   background-color: rgb(251, 251, 251);
}

QProgressBar {
   height: 24px;
   font-weight: bold;
   border-radius: 5px;
   border: 1px solid rgb(205, 205, 205);
   background-color: rgb(251, 251, 251);
}

QProgressBar::chunk{
   border-radius: 5px;
   background-color: rgb(68, 138, 201);
}

QPushButton {
   font-weight: bold;
   border-width: 0px;
   color: rgb(68, 138, 201);
   background-color: transparent;
}

QPushButton:!enabled {
   color: rgb(117, 117, 117);
}

QPushButton:hover:!pressed {
   color: rgb(51, 110, 162);
}

QPushButton:pressed {
   color: rgb(39, 85, 125);
}

```

There is still some room for improvement in my implementation (e.g. work with the layout spacings). @nuttyartist, could you tell me what point sizes are you using for the labels in your UI designs?

**Comment by theshadowx** [comment]
I think instead of using black, better --> rgb(26, 26, 26)

you can add this to remove the window decoration 
```
#ifdef Q_OS_LINUX
    this->setWindowFlags(Qt::Window | Qt::FramelessWindowHint);
#elif _WIN32
    this->setWindowFlags(Qt::CustomizeWindowHint);
#elif __APPLE__
    this->setWindowFlags(Qt::Window | Qt::FramelessWindowHint);
#else
#error "We don't support that version yet..."
#endif
```

**Comment by alex-spataru** [comment]
@theshadowx Thanks for the code, I've changed the colors, removed the window decorations and implemented the functions to drag the window (I used the same code as in the MainWindow).

Here is a screenshot with the result:

screenshot

**Question**: Do I need to write some code to ensure that the window shadow is shown on all platforms?

**Comment by nuttyartist** [comment]
Just checked your updated repo, it looks kinda different from your screenshot. Mainly the spacing and the fonts, I'll say.
screenshot from 2016-11-13 23 37 25

The size of the font in points: title - 25pt (Roboto Medium), versions - 14pt (Roboto Regular), What's new - 14pt (Roboto Medium), QTextBrowser - 14pt (Arimo Regular), Close & Update - 15pt (Roboto Medium)
The color of the fonts should be rgb(26, 26, 26) like the @theshadowx said (except the QTextBrowser).

Also, the app is crashing when I'm clicking on "Update".
"The program has unexpectedly finished."
Do you get that too?

Also, you should use the Qt::PointingHandCursor flag upon hovering the buttons, rather than the Qt::ClosedHandCursor flag.

P.S. I've been on a busy schedule for the last 2 weeks that afford me to work on Notes only at the late night. I will soon try to make room for it in the day too.

Thanks Alex!

**Comment by alex-spataru** [comment]
I will change the widget flags in the QTextBrowser to ensure that it looks good on all platforms. Also, I do not have problems while clicking the "Update" button. I am testing under OS X, what OS/distro are you using? If you have time, could you run the debugger to see where the application crashes?

I will change the cursor flag while hovering the buttons, I have already changed the color of the labels to rgb(26, 26, 26).

Thanks for the feedback!

**Comment by nuttyartist** [comment]
I'm using Linux - Elementary OS. Currently, I can't, I'll try to give it a shot when I'll find time. 
@theshadowx If you're using Linux, are you getting the error I've reported too?

Alrighty. And about what you've asked earlier about if you should provide custom shadows for other platforms, @theshadowx have implemented custom shadows well, we just need to think when and if we should show them (on what os/distro etc...), then we'll just inherit it from that.

**Comment by alex-spataru** [comment]
@nuttyartist I have made the appropriate changes (regarding styling and font sizes). I will try to reproduce your error in a virtual machine.

**Comment by nuttyartist** [comment]
That's how it looks:
screenshot from 2016-11-14 00 29 32
Now, I'm trying to play around with the font size in the QtCreator updaterwindow.ui but to no success, I can't change it for some reason. I think that maybe the pt I gave you are actually px, and thus needs to be converted. (But I can't check that)

When clicking and dragging the window, it moves well, but upon releasing the cursor doesn't change back to default. And the Qt::PointingHandCursor flag doesn't show up upon hovering the buttons.

Also, the white box - QTextBrowser, looks kinds in the 90's. Maybe needs a bit more love from the CSS?

(Going to sleep now... :))

**Comment by theshadowx** [comment]
Here is what I got : (I modified the bottom buttons to be flat)

selection_261

**Comment by theshadowx** [comment]
I think the font size should use px instead of pt

**Comment by nuttyartist** [comment]
@theshadowx cool, the fonts size is of course too big in the screenshot.

@alex-spataru send a PR to the automatic branch with your latest changes, then the @theshadowx push your modifications to the automatic branch. We'll work then on finishing the aesthetics and fix the functionality side of things (the crashing on Linux).

**Comment by theshadowx** [comment]
@nuttyartist  @alex-spataru what is the resolution of your screen ?

**Comment by nuttyartist** [comment]
1366 x 768

**Comment by alex-spataru** [comment]
I will make a pull request with my modifications (also, I will use px instead of pt in the stylesheet). My screen resolution is  1280 x 800.

**Pull request closed without merging**
