### PR TITLE
Update linux build instructions to include Ubuntu 23.04

### PR DESCRIPTION
**Pull request by glpzzz**
Without `qml6-module-qtdatavisualization` is not possible to build in Ubuntu 23.04

### CODE REVIEW

**Comment by zjeffer** [comment]
Is that package not part of a group package by any change? Would be nice if we could just specify qt6-base or something

**Comment by glpzzz** [comment]
I'm not 100% sure, but until I installed `qml6-module-qtdatavisualization` specifically I was receiving the same error mentioned here https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1905437.html

**Comment by glpzzz** [comment]
For Qt5

```bash
$ apt-cache rdepends search qml-module-qtdatavisualization qml-module-qtdatavisualization
qml-module-qtdatavisualization
Reverse Depends:
  qtdatavisualization5-examples
```

For Qt6

```bash
$ apt-cache rdepends search qml6-module-qtdatavisualization
qml6-module-qtdatavisualization
Reverse Depends:
```

In both cases, it seems they have to be explicitly installed

**Comment by guihkx** [comment]
It's very weird that you need `qml6-module-qtdatavisualization` to build the app on Ubuntu 23.10.

I ran `git grep DataVisualization` on our repo and we don't even reference it anywhere. :thinking: 

Also, based on the result of [this build](https://github.com/guihkx/notes/actions/runs/5697046707/job/15443161615) that ran on a clean, container image of Ubuntu 23.04, the list of packages we need for a successful Qt 6 build, is:

- `gcc`
- `cmake`
- `qt6-base-private-dev`
- `qt6-declarative-dev`
- `libgl-dev`

And as a side note, I don't think it's worth documenting packages for a Qt 5 build if the target distro already has Qt 6 in its repositories.

**Comment by glpzzz** [comment]
I just show the output for qt5 package as an example because the output list one reverse dependency. The package for qt6 doesn't. 

I'll try to reproduce in a fresh Ubuntu and find out if I can reproduce my issue.

First I did was install dependencies listed in doc:
- `sudo apt install cmake gcc git qt6-base-private-dev qt6-declarative-dev libgl-dev`
- `sudo apt install libqt6network6 libqt6sql6 libqt6widgets6 qml6-module-qtqml-workerscript qml6-module-qtquick-controls qml6-module-qtquick-particles qml6-module-qtquick-templates qt6-qpa-plugins`

and the the build steps as listed in `/docs/build_on_linux.md`

on the cmake step, then the error shown in the link listed before.

Good is working. I'll try to obtain more info and post here.

**Comment by nuttyartist** [comment]
What should we do about this?

**Comment by guihkx** [comment]
> What should we do about this?

Well, we've been using Ubuntu 23.04 on our CI workflow for quite a while now, and [the current list of build dependencies](https://github.com/nuttyartist/notes/actions/runs/5948599412/job/16132713400#step:6:3) come directly [from our documentation](https://github.com/nuttyartist/notes/blob/f4ac893db6c141dd6222b3d3c4d822e13993d182/docs/build_on_linux.md#requirements:~:text=Ubuntu%2022.04%20%2D%2023.04).

Therefore, I still maintain that the list is accurate.

@glpzzz It'd be great if you could revisit this.

**Comment by glpzzz** [comment]
Fresh Ubuntu 23.04 installed on VirtualBox Machine

- Installed listed dependencies (cmake gcc git qt6-base-private-dev qt6-declarative-dev libgl-dev libqt6network6 libqt6sql6 libqt6widgets6 qml6-module-qtqml-workerscript qml6-module-qtquick-controls qml6-module-qtquick-layouts qml6-module-qtquick-particles qml6-module-qtquick-templates qml6-module-qtquick-window qt6-qpa-plugins)

- `git clone` and `cd notes`
- `mkdir build` and `cd build`
- on the following `cmake` command I'm getting the following output now:

```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:24 (project):
  No CMAKE_CXX_COMPILER could be found.
 
  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
 
 
-- Configuring incomplete, errors occurred!
See also "/home/vboxuser/notes/build/CMakeFiles/CMakeOutput.log".
See also "/home/vboxuser/notes/build/CMakeFiles/CMakeError.log".
```

**Comment by guihkx** [comment]
@glpzzz Thank you for revisiting!

>```
>-- The CXX compiler identification is unknown
>CMake Error at CMakeLists.txt:24 (project):
>  No CMAKE_CXX_COMPILER could be found.
>```

Ugh, that's my bad.

On Arch and Fedora, `gcc` automatically includes `g++` (which fixes this error), but on Debian-based distros we need to install `g++` explicitly. As you mentioned, installing `build-essential` works, but I personally dislike doing that because it installs some extra stuff we don't use.

And our CI for 23.04 wasn't hitting this problem because `g++` was being installed automatically as a dependency of `lintian` (which we use to validate our deb package), and I totally missed that! :grimacing: 

So that's indeed a genuine mistake in our documentation, which I think can be easily fixed by replacing `gcc` by `g++` on the list of build dependencies of Ubuntu.

I'd appreciate if you could do that for us!

> When executing the application from command line, I'm getting this output:
>```
>qrc:/qt/qml/EditorSettings.qml:228:21: Type FontChooserButton unavailable 
>```

That's a problem I genuinely could not reproduce. Here's a quick step-by-step build I did in 'Live CD' mode on Ubuntu 23.04:

https://github.com/nuttyartist/notes/assets/626206/f7a63e61-4311-4442-a88a-d7822cd58db1

**Comment by glpzzz** [comment]
> As you mentioned, installing `build-essential` works, but I personally dislike doing that because it installs some extra stuff we don't use

Great you have the required package identified.

> That's a problem I genuinely could not reproduce. Here's a quick step-by-step build I did in 'Live CD' mode on Ubuntu 23.04

Let me try to obtain more info on why the application don't behave the same for me.

**Comment by guihkx** [comment]
> Let me try to obtain more info on why the application don't behave the same for me.

Thanks! Also, just a heads up, there have been documentation updates in `master`, so your branch needs to be rebased and file conflicts addressed.

**Comment by zjeffer** [comment]
@glpzzz Hi, this PR has been open for quite a while now. Are the changes still necessary?

**Pull request closed without merging**
