### PR TITLE
Add: New Icon

### PR DESCRIPTION
**Pull request by KevDoy**
Proposed new icon with vector

### CODE REVIEW

**Comment by nuttyartist** [comment]
Hey kevin,

The icon looks great. Only minor changes should be made, replace the yellow color with the color you used here: http://i.imgur.com/zD7bX9R.png, and also make the lines color more bold like in that image.

Also, can you make two versions for comparison, one with rounded corners (like in this pull request) and one without?

Thanks!

**Comment by KevDoy** [comment]
screen shot 2016-04-18 at 2 16 18 pm
screen shot 2016-04-18 at 2 16 42 pm


Adjustments made - I think the rounded corners give it a unique flare to stand out.

**Comment by nuttyartist** [comment]
The colors look good now.
Could you get rid of the white background so I could test it on my dock?

**Comment by KevDoy** [comment]
size?

**Comment by nuttyartist** [comment]
Do you mean size for testing in the dock?
If so, 48px

**Comment by KevDoy** [comment]
here, let's just do SVG -

**Comment by nuttyartist** [comment]
Alright, the rounded corners looks better, we'll go with that.

2 Things left that should be open on separate issues:
1. Making different resolutions like: 16x16, 16x16@2x etc...
2. Supporting that resolution for each platform by the way we package the app/code.

Before I merge, it says there are 4 files changed when there should be only one: notes_icon.png (convert the svg to png). After you will do that I will convert that to .ico and .icns (Or you can do that if you want).

**Comment by KevDoy** [comment]
I've been extremely swamped, I'll just undo those commits, commit just the svg and png. with the svg you should be able to get any size you wish!

**Comment by KevDoy** [comment]
I'm having issues on my end 😞

**Comment by nuttyartist** [comment]
Just delete the "notes.svg", so only "notes_icon.png" is there.

**Comment by nuttyartist** [comment]
Kevin, It would be great if you could send a pull request to the dev branch (see #43). So I'm gonna close this issue.

**Pull request closed without merging**
