### PR TITLE
Fix incompatibility with Qt 6.6

### LINKED ISSUE #652: Editor settings window is broken with Qt 6.6
Qt 6.6 was released just a few days ago, and while Notes builds just fine with it, the Editor Settings window won't open anymore:

https://github.com/nuttyartist/notes/assets/626206/fabae2bd-3973-4039-a3f5-6e9c723b891e

This is the output I get when I open the app using the terminal:

```
$ notes
qrc:/qt/qml/EditorSettings.qml:429:21: Type OptionItemButton unavailable 
                         OptionItemButton { 
                         ^
qrc:/qt/qml/OptionItemButton.qml:15:5: Cannot override FINAL property 
         property bool enabled: true 
         ^
qrc:/qt/qml/kanbanMain.qml:615:33: Type OptionItemButton unavailable 
                                     OptionItemButton { 
                                     ^
qrc:/qt/qml/OptionItemButton.qml:15:5: Cannot override FINAL property 
         property bool enabled: true 
         ^
Database: connection ok
```

This was tested on commit 10bed3427934456711a7e49b05ecb47fff617666 and on Linux. I haven't tested on other platforms.

### PR DESCRIPTION
**Pull request by dmytrovoytko**
Please consider this PR to fix #652  so Kanban view works again!

### CODE REVIEW

**Review by guihkx — APPROVED** [review]
Thank you so much for working on this! I tested your changes locally with Qt 6.6.1 and I can confirm they fix #652.

Pinging @nuttyartist though, since he knows this QML stuff better.

**Comment by zjeffer** [comment]
Great that you fixed this! 

I don't understand *why* it fixes it, though. Do you have any documentation explaining why `enabled` doesn't work but `isEnabled` does? Is `enabled` a built-in property we cannot use?

**Comment by guihkx** [comment]
> Is `enabled` a built-in property we cannot use?

Judging by the error message, that seems to be exactly the case (at least with Qt 6.6):

```
qrc:/qt/qml/OptionItemButton.qml:15:5: Cannot override FINAL property 
         property bool enabled: true 
         ^
```

**Comment by zjeffer** [comment]
Shouldn't we then, instead of renaming it to `isEnabled`, remove the line where we (re)define the `enable` property, and use the built-in one instead?

**Comment by zjeffer** [comment]
Created a new PR to test the builds: https://github.com/nuttyartist/notes/pull/657

If it works on previous versions, we can close this and merge 657 instead.

**Comment by zjeffer** [comment]
#657 works, closing in favour of that PR.

Thanks @dmytrovoytko!

**Comment by nuttyartist** [comment]
Thanks everybody (: I was programming this just when I started studying QML so some of the Kanban code is still rough around the edges. @zjeffer, your PR works just fine. And thanks @dmytrovoytko for spotting this.

**Pull request closed without merging**
