### PR TITLE
Added deployment to GitHub on tags

### PR DESCRIPTION
**Pull request by bjorn**
This is a renewed attempt at doing #249 (which was merged, but I removed that change again).

This is still not working (check out https://travis-ci.org/nuttyartist/notes/jobs/646594086 for example)

```
/home/travis/.travis/functions: eval: line 110: syntax error near unexpected token `then'
/home/travis/.travis/functions: eval: line 110: `    if [[ "$QT_BASE" == "xenial" || "$QT_BASE" == "yakkety" || "$QT_BASE" == "zesty" ]]; then mv deb/notes*.deb deb/notes_${NOTES_VERSION}_amd64-${QT_BASE}.deb curl --upload-file deb/notes*.deb https://transfer.sh/notes_${NOTES_VERSION}_amd64-${QT_BASE}.deb elif [ "$QT_BASE" == "appimage" ]; then mv Notes-*.AppImage notes_${NOTES_VERSION}_amd64.AppImage curl --upload-file ./notes_*.AppImage https://transfer.sh/notes_${NOTES_VERSION}_amd64.AppImage elif [ "$QT_BASE" == "snap" ]; then mv snap/notes*.snap snap/notes_${NOTES_VERSION}_amd64.snap curl --upload-file snap/notes*.snap https://transfer.sh/notes_${NOTES_VERSION}_amd64.snap fi '
```

Will need more fiddling, but I'm out of time, sorry. I've removed the mess from `dev`.

### CODE REVIEW

**Comment by nuttyartist** [comment]
No problem, it's alright. When you gonna fix this problem I'm gonna use the artifacts to release the new version. It's been a long time.

**Comment by bjorn** [comment]
Right, so in the end this didn't work out due to me fighting with syntax issues in the bash script. Somebody who can write bash scripts could fix it, or eventually I'll find some time for it in the evening to fix that.

In the meantime, somebody could also look into making the setup created by the AppVeyor build upload directly to GitHub (see https://www.appveyor.com/docs/deployment/github/). And I noticed you're releasing a `.app` for macOS, but where is this getting built? An autobuild could be set up on either Travis CI or AppVeyor, since they both also support macOS.

**Comment by nuttyartist** [comment]
Hey, @bjorn!

I'm building the .app for macOS on my machine and then packing for dmg using macdeplyqt, also on my machine. Can't Travis/Github handle macOS? I thought they can't because of licenses, etc...

I'll wait for you to accomplish creating these artifacts successfully. 👍

**Comment by Waqar144** [comment]
Travis / Github can handle dmg. We do it at QOwnNotes

**Comment by nuttyartist** [comment]
> Travis / Github can handle dmg. We do it at QOwnNotes

Can it also compile?

**Comment by bjorn** [comment]
> Can it also compile?

Well, you're already compiling for macOS on GitHub, see https://github.com/nuttyartist/notes/blob/dev/.github/workflows/macos.yml. :-)

Unfortunately I got a cold and am generally busy, but I just figured out what went wrong with my syntax. I had removed some semicolons which I thought were superfluous, but they're needed because the script is merged into a single line when the script is executed by bash. Let's see if it's solved now.

**Comment by bjorn** [comment]
So, the syntax issues are now resolved, but we've got at least one more issue, the renaming is not working:
```
mv: cannot move ‘deb/notes_1.0.0_amd64.deb’ to ‘deb/notes_1.0.0-git1d634c5_amd64-yakkety.deb’: Permission denied
```
I guess this is due to the `.deb` being built inside a Docker container, which apparently uses a different user. @theshadowx, it seems you've been setting up these Docker builds. Do you know what we could do about this?

**Comment by nuttyartist** [comment]
I hope you will get better soon! @bjorn. Okay, waiting for you to resolve it with @theshadowx.

**Comment by theshadowx** [comment]
@bjorn I'm working on it

**Comment by nuttyartist** [comment]
#254 seems to fix #248. What shall we do with this PR?

**Comment by theshadowx** [comment]
Wait till the snapcraft is updated

**Comment by bjorn** [comment]
Alright, nice job fixing up the remaining issues and merging the configuration @theshadowx!

So I've merged this, and I agree we should first try to fix up the snap and then we'll try to tag again and see if it all works out.

**Pull request merged**
