### PR TITLE
Fix Ctrl-del deletes notes instead of text #214

### PR DESCRIPTION
**Pull request by Waqar144**
Notes can now be deleted with `Ctrl+Shift+Del`

### CODE REVIEW

**Comment by theshadowx** [comment]
This won't work in windows as it will show a menu for log off

**Comment by Waqar144** [comment]
> This won't work in windows as it will show a menu for log off

Ideally it should work on focus, the widget which has focus shortcut should be triggered for it only

**Comment by theshadowx** [comment]
I am open to any proposal

**Comment by Waqar144** [comment]
TBH, `Ctrl+shift+del`, doesn't seem like a good shortcut for a simple action like deleting notes. Idk why i did that even.

Anyways, One way could be to have a different shortcut, that doesn't conflict with the default shortcuts of QTextEdit. Maybe `Ctrl + D` ?.

**Comment by nuttyartist** [comment]
I discuss in issue #214 my reasoning behind the change. Many people emailed us about mistakingly deleting their notes. Is ctrl+shift+delete not gonna work cross-platform? Why?

**Comment by Waqar144** [comment]
> I discuss in issue #214 my reasoning behind the change. Many people emailed us about mistakingly deleting their notes. Is ctrl+shift+delete not gonna work cross-platform? Why?

Because global shortcuts take priority over app shortcuts.

**Comment by nuttyartist** [comment]
@Waqar144 can you change it to Ctrl+D and I'll merge this?

**Comment by Waqar144** [comment]
Alright, here you go!

**Comment by nuttyartist** [comment]
Merging... Thank you @Waqar144!

**Pull request merged**
