### PR TITLE
Build universal x86_x64/arm64 Qt 6 binaries on macOS

### PR DESCRIPTION
**Pull request by guihkx**
Disabled for Qt 5 builds at the moment, as it's only available on commercial builds: https://www.qt.io/blog/qt-on-apple-silicon

This is part of #411.

### CODE REVIEW

**Comment by nuttyartist** [comment]
Awesome! I have an M1 Mac lying around, so I can test this. Qt5 is not needed, so Qt6 is fine.

Where can I grab the artifacts from to test this? Only after merging?

**Comment by guihkx** [comment]
Both arm64 and x86_64 binaries are actually bundled into a single binary, so you can test the x86_64 dmg should work on both architectures.

I should probably rename the artifact to include arm64, though...

**Comment by nuttyartist** [comment]
> Both arm64 and x86_64 binaries are actually bundled into a single binary, so the x86_64 dmg should work on both architectures.
> 
> I should probably rename the artifact to include arm64, though...

Ah perfect. Yes, that will be good. Something with both x86_64 and arm64, or universal.

**Comment by guihkx** [comment]
Done. Feel free to merge once you make sure it works.

**Comment by nuttyartist** [comment]
Great I'll try to test it tonight.

**Comment by nuttyartist** [comment]
It works very well on a Mac and runs natively on Arm now (I made sure it's not running in Rosetta 2).

But one thing that needs to change is that I always package Notes on Macs with the name "Notes Better" since all Macs come pre-installed with a "Notes" app so In order to not conflict with the app, I rename the package to "Notes Better," haha. So we should keep doing this in the Releases as well.

**Comment by guihkx** [comment]
I see... Do you think it's enough to change the [CFBundleName property](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlename)?

**Comment by nuttyartist** [comment]
So we can apparently drag the app to the "Applications" folder without causing any trouble except, oddly enough the app runs, but the indicator in the task manager is associated with the pre-installed Apple Notes app (our icon doesn't show).
I tested just changing `CFBundleName` to 'Notes Better' (also `CFBundleExecutable`) while keeping the app package name "Notes" but the same happens. Only when changing the package name it works properly.

**Comment by guihkx** [comment]
Hmm, then I'm thinking it might just be a matter of renaming the `.app` folder from `Notes.app` to `Notes Better.app`.

At least that's what was done in v2.0.0, as `CFBundleExecutable` and `CFBundleName` are still set to `Notes`.

Let's try that first...

**Comment by nuttyartist** [comment]
Sure, sounds good! Feel free to merge once you're ready.

**Comment by guihkx** [comment]
I tested on a Big Sur VM and it seems to work, so let's merge this.

**Pull request merged**
