### PR TITLE
Replace `Q_OS_LINUX` checks by `Q_OS_UNIX && !Q_OS_MACOS`

### LINKED ISSUE #410: Replace Q_OS_LINUX in the code with Q_OS_UNIX
This should be no-op on GNU/Linux while simplifying packaging for other Unix-like systems, *BSD, et al.  While explicit FreeBSD support had been added in eda71ec, IMHO it should be generalized.

### PR DESCRIPTION
**Pull request by guihkx**
This should make our code more *nix friendly.

Closes #410

### CODE REVIEW

**Review by bjorn — APPROVED** [review]

**Comment by nuttyartist** [comment]
Nice 👍

**Comment by nuttyartist** [comment]
Why does it say some checks were not successful?

**Comment by bjorn** [comment]
> Why does it say some checks were not successful?

The macOS Homebrew Qt 6 build was cancelled due to #497.

**Comment by nuttyartist** [comment]
Ahh ok.

**Pull request merged**
