### PR TITLE
Bumping app version to 1.5.0

### PR DESCRIPTION
**Pull request by bjorn**

### CODE REVIEW

**Comment by bjorn** [comment]
The snap is still called `notes_1.0.0_amd64.snap` because it depends on the release being tagged. Unfortunately, the uploads again show "Could not save metadata", which indicates a problem at transfer.sh so right now I can't test the snap or Debian packages.

**Comment by theshadowx** [comment]
Deb dependecies should be updated

**Comment by bjorn** [comment]
@theshadowx I'm not really familiar with Debian packaging. If you think it should be done as part of the version bump, please feel free to push relevant commits here.

**Comment by nuttyartist** [comment]
@bjorn @theshadowx Can we progress on this?

**Comment by bjorn** [comment]
I'm afraid I don't have enough experience with Debian packaging and too busy to help out currently. Also it is unclear to me how the needed Deb updates relate to this pull request. I think it could just be merged independently.

**Comment by nuttyartist** [comment]
Excuse me for not responding for a long time. Yes, let's merge this.

**Comment by nuttyartist** [comment]
So, after this merge we should have all the artifacts generated properly (except Debian package which we need to update its dependencies)?

**Pull request merged**
