### PR TITLE
add IDE gitignore rules for IDE (CLion and Visual Studio Code)

### PR DESCRIPTION
**Pull request by stevenleeS0ht**
CLion and Visual Studio Code are the most popular two IDEs for C++ development. 

It would be nice to add gitignore rules for those IDE.

@nuttyartist , this commit will not affect any existing developers.

### CODE REVIEW

**Review by zjeffer — COMMENTED** [review]
You also added IntelliJ and Android Studio stuff, which isn't necessary. I think this can be cleaned up a bit to only include what is actually necessary (makes it easier to maintain too).

**Comment by stevenleeS0ht** [comment]
@zjeffer 

The content is derived from <https://www.toptal.com/developers/gitignore/>. Which `CLion+all` and `VisualStudioCode` are toggled.

Keep this original content without any change or delete would helpful for future developers modify the content in `.gitignore`.

In other words, if there is content update in <https://www.toptal.com/developers/gitignore/>. Another developer can simply select all the content in this section and replace it with updated contents, without read it line-by-line.

And for the other developers, they only need to know that this section is copied from <https://www.toptal.com/developers/gitignore/> without knowing the meaning of each line.

**Comment by nuttyartist** [comment]
This needs to be cleaned up considerably, @stevenleeS0ht. Also, please remove all the unnecessary "toptal" related comments. Please **narrow it down to only the VSCode and CLion related files**, and please describe in this thread a short summary about those files.

**Comment by stevenleeS0ht** [comment]
@nuttyartist , @zjeffer , is it OK now?

**Comment by stevenleeS0ht** [comment]
@nuttyartist , I just further trim down the `.gitignore` files, it now looks more concise.

If this is OK now, please merge it. 

I want to give a try on <https://github.com/nuttyartist/notes/issues/682>. Without this pull request merged, I cannot start a new pull request on new feature.

**Review by zjeffer — APPROVED** [review]
Looks much better now.

> I want to give a try on https://github.com/nuttyartist/notes/issues/682. Without this pull request merged, I cannot start a new pull request on new feature.

I don't understand why you would need this PR merged to be able to start working on that? When commiting on a branch, you can simply not execute `git add .`, and instead only `git add` what you want to add to the commit?

**Review by nuttyartist — APPROVED** [review]

**Comment by nuttyartist** [comment]
Looks good now, thanks @stevenleeS0ht. Merging...

**Pull request merged**
